CREATE TABLE "GCG_3531_APRVL_CERT"(
 "GS_NUMBER" VARCHAR(7) NOT NULL ,
 "M_TYPE" INTEGER NOT NULL ,
 "VEND_CUST" VARCHAR(6) NOT NULL ,
 "AMOUNT" DOUBLE NOT NULL ,
 "AMOUNT_ORIGINAL" DOUBLE ,
 "DATE_DUE" DATE NOT NULL ,
 "ORIGINATOR" VARCHAR(8) NOT NULL ,
 "APPROVER" VARCHAR(8),
 "APPROVED_DATE" DATETIME);

CREATE TABLE "GCG_3531_APRVRS_CERT"(
 "GS_USER" VARCHAR(8) NOT NULL ,
 "APPROVER" VARCHAR(8) NOT NULL ,
 "M_TYPE" INTEGER);

CREATE TABLE "GCG_3531_DOL_LMT"(
 "GS_USER" VARCHAR(8) NOT NULL ,
 "LIMIT" DOUBLE NOT NULL ,
 "M_TYPE" INTEGER);